<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    </head>

    <style>

        body {
          background: #fff;
        }
        .container {
          width: 60%;
          margin: 10px auto;
          background: #333;
          border-radius: 6px;
          overflow: hidden;
          box-shadow: 0 0 4px rgba(0, 0, 0, 0.4), 0 4px 4px rgba(0, 0, 0, 0.2);
          border: 2px solid #252af3;
        }
        .container input {
          background: transparent;
          border: 0;
          font-size: 30px;
          color: #fff;
        }
        .suggestions {
          border-top: 2px solid #252af3;
          display: none;
        }
        .suggestions.show {
          display: block;
        }
        .suggestions > div {
          padding: 15px;
          font-size: 20px;
          color: #fff;
          border-top: 1px solid #666;
          cursor: pointer;
        }
        .suggestions > div:hover, .suggestions > div.selected  {
          background-color: #1e4dd4;
        }
        .emphy {
          width: 50%;
          margin: 40px auto;
          text-align: center;
          color: #fff;
        }

    </style>

    <body>

      <h1>Task List from MySQL DB</h1>

      <p class="emphy">Type a name</p>
        <div class="container">
          <input class="search-input" type="text" placeholder="Search here..." />
          <div class="suggestions">
          </div>
        </div>

    </body>

    <!-- <script src="templates/JS/JS.js"></script> -->

    <script>

        var selectedSuggestionIndex = -1;
        const searchInput = document.querySelector('.search-input');
        const suggestionsPanel = document.querySelector('.suggestions');

        function resetSelectedSuggestion() {
          for (var i = 0; i < suggestionsPanel.children.length; i++) {
            suggestionsPanel.children[i].classList.remove('selected');
          }
        }
        searchInput.addEventListener('keyup', function(e) {
          if (e.key === 'ArrowDown') {
            resetSelectedSuggestion();
            selectedSuggestionIndex = (selectedSuggestionIndex < suggestionsPanel.children.length - 1) ? selectedSuggestionIndex + 1 : suggestionsPanel.children.length - 1;
            suggestionsPanel.children[selectedSuggestionIndex].classList.add('selected');
            return;
          }
          if (e.key === 'ArrowUp') {
            resetSelectedSuggestion();
            selectedSuggestionIndex = (selectedSuggestionIndex > 0) ? selectedSuggestionIndex -1 : 0;
            suggestionsPanel.children[selectedSuggestionIndex].classList.add('selected');
            return;
          }
          if (e.key === 'Enter') {
            searchInput.value = suggestionsPanel.children[selectedSuggestionIndex].innerHTML;
            suggestionsPanel.classList.remove('show');
            selectedSuggestionIndex = -1;
            return;
          }

          const input = searchInput.value;
          suggestionsPanel.innerHTML = '';
          /*const suggestions = countries.filter(function(country) {
            return country.name.toLowerCase().startsWith(input.toLowerCase());
          });*/

          // API ENDPOINT /////////////////////////////////////////////////////////////////////////////////////
          fetch('http://localhost:8081/client/search?term=' + input)

          .then(response => response.json())
          .then(suggestions => {
            suggestionsPanel.classList.add('show');
            suggestions.forEach(function(suggested) {
              const div = document.createElement('div');

              // div.innerHTML = suggested.< name of DB column > //////////////////////////////////////////////
              div.innerHTML = suggested.task;

              div.setAttribute('class', 'suggestion');
              suggestionsPanel.appendChild(div);
            });
          });
          if (input === '') {
            suggestionsPanel.innerHTML = '';
          }
        });

        document.addEventListener('click', function(e) {
          if (e.target.className === 'suggestion') {
            searchInput.value = e.target.innerHTML;
            suggestionsPanel.classList.remove('show');
          }
        });

    </script>

</html>
