<?php

// PHP code here

?>


<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>Slim CREATE</title>
    </head>
    <body>

        <h1>Create Task</h1>

        <form action="/todo/create" method="post">

            <!-- id:             <input type="text" name="id" value="id"><br> -->
            task:           <input type="text" name="task"><br>
            status:         <input type="text" name="status"><br>
            <!-- created_at:     <input type="text" name="created_at" value="created at"><br> -->

            <br>
            <input type="submit" name="Submit" value="CREATE">

        </form>

    </body>

</html>
