<?php

// PHP code here

?>


<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>Slim DELETE</title>
    </head>
    <body>

        <h1>Delete Task</h1>

        <form action="/todo/delete" method="post">

            id:     <input type="text" name="id"><br>

            <br>
            <input type="submit" name="Submit" value="DELETE">

        </form>

    </body>

</html>
