<?php

// PHP code here

?>


<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>Slim CREATE</title>
    </head>
    <body>

        <h1>Tasks</h1>

        <table class="table table-stripped">
          <thead>
            <tr>
              <th>Name</th>
              <th>Job</th>
              <th>E-mail</th>
              <th>Age</th>
            </tr>
          </thead>

    </body>

</html>
