<?php

// PHP code here

?>


<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>Slim CREATE</title>
    </head>
    <body>

        <h1>Update Task</h1>

        <form action="/todo/update" method="post">

            id:     <input type="text" name="id"><br>
            task:   <input type="text" name="task"><br>

            <input type="submit" name="Submit" value="UPDATE">

        </form>

    </body>

</html>
